/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wellen_SAM */

#ifndef _Included_wellen_SAM
#define _Included_wellen_SAM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wellen_SAM
 * Method:    get_samples
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_wellen_SAM_get_1samples
  (JNIEnv *, jobject);

/*
 * Class:     wellen_SAM
 * Method:    set_mouth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_set_1mouth
  (JNIEnv *, jobject, jint);

/*
 * Class:     wellen_SAM
 * Method:    set_pitch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_set_1pitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     wellen_SAM
 * Method:    set_sing_mode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_set_1sing_1mode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     wellen_SAM
 * Method:    set_speed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_set_1speed
  (JNIEnv *, jobject, jint);

/*
 * Class:     wellen_SAM
 * Method:    set_throat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_set_1throat
  (JNIEnv *, jobject, jint);

/*
 * Class:     wellen_SAM
 * Method:    speak
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_speak
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     wellen_SAM
 * Method:    speak_ascii
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_speak_1ascii
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
