/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wellen_SAM */

#ifndef _Included_wellen_SAM
#define _Included_wellen_SAM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wellen_SAM
 * Method:    printMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wellen_SAM_printMethod
  (JNIEnv *, jobject);

/*
 * Class:     wellen_SAM
 * Method:    trueFalse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_wellen_SAM_trueFalse
  (JNIEnv *, jobject);

/*
 * Class:     wellen_SAM
 * Method:    power
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_wellen_SAM_power
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     wellen_SAM
 * Method:    returnAByteArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_wellen_SAM_returnAByteArray
  (JNIEnv *, jobject);

/*
 * Class:     wellen_SAM
 * Method:    stringManipulator
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wellen_SAM_stringManipulator
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     wellen_SAM
 * Method:    get_samples
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_wellen_SAM_get_1samples
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
